services:
  api:
    container_name: conversion-backend
    build:
      context: conversion-backend/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  web:
    container_name: conversion-frontend
    build:
      context: conversion-frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      api:
        condition: service_started
    volumes:
      - ./conversion-frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
