name: Deno Backend Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    merge_group:
    types: [checks_requested]

permissions:
  contents: read

defaults:
  run:
    working-directory: ./conversion-backend

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      # Uncomment this step to verify the use of 'deno fmt' on each commit.
      # - name: Verify formatting
      #   run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno test -A
