name: Yarn Frontend Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

defaults:
  run:
    working-directory: ./conversion-frontend

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Yarn
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 22

      - name: Run linter
        run: yarn lint

      - name: Run tests
        run: yarn test
